# 开发环境Docker Compose配置
version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: build/backend/Dockerfile
    container_name: krinol-backend-dev
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SECRET_KEY=dev-secret-key
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ../backend:/app
      - ../backend/uploads:/app/uploads
    networks:
      - krinol-dev-network

  frontend:
    build:
      context: ..
      dockerfile: build/frontend/Dockerfile
    container_name: krinol-frontend-dev
    ports:
      - "3000:80"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - krinol-dev-network

  db:
    image: mysql:8.0
    container_name: krinol-db-dev
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data_dev:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - krinol-dev-network

volumes:
  mysql_data_dev:

networks:
  krinol-dev-network:
    driver: bridge
